### ISSUE TITLE
Cannot get autocomplete to work on Ubuntu 15.10

### ISSUE THREAD

**Issue by ananttrivedi** [ternjs/tern_for_sublime#109]
It seems tern_for_sublime is setup correctly. 
When I start sublime, I see following on the console:
```
reloading plugin tern_for_sublime.tern
plugins loaded
Package Control: No updated packages
```
I created a test js file with `myArray = [];` array defined. Now, when I type the variable I defined (`myArray`) I get the following error:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/ana/.config/sublime-text-3/Packages/tern_for_sublime/tern.py", line 61, in on_query_completions
    completions, fresh = ensure_completions_cached(pfile, view)
  File "/home/ana/.config/sublime-text-3/Packages/tern_for_sublime/tern.py", line 412, in ensure_completions_cached
    data = run_command(view, {"type": "completions", "types": True, "includeKeywords": True})
  File "/home/ana/.config/sublime-text-3/Packages/tern_for_sublime/tern.py", line 291, in run_command
    port, port_is_old = server_port(pfile.project)
  File "/home/ana/.config/sublime-text-3/Packages/tern_for_sublime/tern.py", line 158, in server_port
    started = start_server(project)
  File "/home/ana/.config/sublime-text-3/Packages/tern_for_sublime/tern.py", line 170, in start_server
    proc = subprocess.Popen(tern_command + tern_arguments, cwd=project.dir, env=env,
TypeError: Can't convert 'list' object to str implicitly
```
I have ubuntu 15.10.

**Comment by marijnh** [comment]
`sublimetern` is not this package, but another, deprecated package that does something similar.
