### ISSUE TITLE
TypeError: Can't convert 'list' object to str implicitly

### ISSUE THREAD

**Issue by max-mykhailenko** [ternjs/tern_for_sublime#146]
Have problem with tern plugin

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 521, in run
    data = run_command(self.view, {"type": "definition", "lineCharPositions": True})
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 295, in run_command
    port, port_is_old = server_port(pfile.project)
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 162, in server_port
    started = start_server(project)
  File "/Users/max/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 174, in start_server
    proc = subprocess.Popen(tern_command + tern_arguments, cwd=project.dir, env=env,
TypeError: Can't convert 'list' object to str implicitly
```

**Comment by marijnh** [comment]
You set `tern_command` to a string, whereas it is expected to be an array of strings.
