### ISSUE TITLE
Autocomplete not working 

### ISSUE THREAD

**Issue by Viterzgir** [ternjs/tern_for_sublime#174]
I'm getting error while edit js file with default .tern-project. Autocomplete suggestions is not working.
https://pastebin.com/JexNfuwJ

**Comment by abepark01** [comment]
I am also getting the same error when I view the console.

OSX 10.12.6
Python 2.7.13 (installed via homebrew)
node 8.5.0 (installed via homebrew)
Homebrew 1.3.2

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 547, in on_deactivated_async
    callback.on_deactivated_async(v)
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 44, in on_deactivated_async
    on_deactivated(view)
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 29, in on_deactivated
    send_buffer(pfile, view)
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 350, in send_buffer
    port = server_port(pfile.project)[0]
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 165, in server_port
    started = start_server(project)
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/tern_for_sublime/tern.py", line 171, in start_server
    if not tern_command: return None
UnboundLocalError: local variable 'tern_command' referenced before assignment
```

**Comment by abepark01** [comment]
I created a PR via #175
